# Site settings
title: Leather Repair Company Ireland
email:
author:
description: Leather Repair Company Ireland
url: https://leatherrepaircompanyireland.com

# Build settings
permalink: :title/
sass:
  sass_dir: css
