# Site settings
title: Leather Care Company Ireland
email:
author:
description: Leather Care Company Ireland
url: http://leathercarecompanyireland.com

# Build settings
permalink: :title/
sass:
  sass_dir: css
